import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/organisms/header";
import Sidebar from "@/components/organisms/sidebar";
import Footer from "@/components/organisms/footer";
import classNames from "classnames";

const roboto_mono = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Portfolio Generated by Nextjs 14",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames("bg-secondary", roboto_mono.className)}>
        <Header />
        <div className="container grid grid-cols-12 gap-4 content-center h-[calc(100vh-140px)]">
          <Sidebar
            links={[
              { name: "About", route: "/about" },
              { name: "Work", route: "/work" },
              { name: "Skills", route: "/skills" },
              { name: "Contacts", route: "/contacts" },
            ]}
          />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
